import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Docusaurus generates the sidebar automatically from the docs/ folder
 * structure (populated at build time from ../docs/ by
 * scripts/sync-docs.mjs — see docs-site/README.md). v1 relies on
 * alphabetical ordering + per-file `sidebar_position` frontmatter rather
 * than a hand-maintained manual sidebar array, so navigation tracks
 * scripts/docs-manifest.json automatically with no sidebar upkeep.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
