#!/usr/bin/env bash
set -euo pipefail
# Agent module test-coverage gate. Same line-coverage-from-coverprofile
# arithmetic as scripts/go-test-coverage.sh (backend's coverage gate), but
# scoped to the agent/ Go module: no encryption-key bootstrapping (agent has
# no equivalent to CHARON_ENCRYPTION_KEY_TEST) and a smaller
# EXCLUDE_PACKAGES set (agent's root/main package only, mirroring
# backend/cmd/api's exclusion precedent).

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
AGENT_DIR="$ROOT_DIR/agent"
COVERAGE_FILE="$AGENT_DIR/coverage.txt"
# Calibrated to the module's actual aggregate line coverage after this PR's
# new tests landed (~65.3% at the time this gate was introduced) per R8:
# the gate must be enforced from a passing baseline, not an arbitrary target
# that would require an unrelated test-writing effort to first go green.
# agent/leash sits at ~44% (pre-existing, out of scope for this PR — see
# docs/plans/current_spec.md Section 3.5) and pulls the aggregate down;
# raising it is a separate, future effort.
MIN_COVERAGE="${CHARON_AGENT_MIN_COVERAGE:-65}"

cd "$AGENT_DIR"

# Packages to exclude from coverage (main package/entrypoint only).
# Mirrors backend/cmd/api's exclusion in scripts/go-test-coverage.sh:
# CLI bootstrap/flag-parsing code that doesn't benefit from unit tests, per
# codecov.yml's "entrypoints and infrastructure code" exclusion precedent.
EXCLUDE_PACKAGES=(
    "github.com/Wikid82/charon/agent"
)

GO_TEST_STATUS=0
TEST_OUTPUT_FILE=$(mktemp)
trap 'rm -f "$TEST_OUTPUT_FILE"' EXIT

if command -v gotestsum &> /dev/null; then
    set +e
    gotestsum --format pkgname -- -mod=readonly -coverprofile="$COVERAGE_FILE" ./... 2>&1 | tee "$TEST_OUTPUT_FILE"
    GO_TEST_STATUS=$?
    set -e
else
    set +e
    go test -v -mod=readonly -coverprofile="$COVERAGE_FILE" ./... 2>&1 | tee "$TEST_OUTPUT_FILE"
    GO_TEST_STATUS=$?
    set -e
fi

if [ "$GO_TEST_STATUS" -ne 0 ]; then
    echo "Warning: go test returned non-zero (status ${GO_TEST_STATUS}); checking coverage file presence"
    echo ""
    echo "============================================"
    echo "FAILED TEST SUMMARY:"
    echo "============================================"
    grep -E "(^--- FAIL:|^FAIL[[:space:]]|^WARNING: DATA RACE|^panic:)" "$TEST_OUTPUT_FILE" || echo "No specific failures captured in output"
    echo "============================================"
fi

# Filter out excluded packages from coverage file
if [ -f "$COVERAGE_FILE" ]; then
    echo "Filtering excluded packages from coverage report..."
    FILTERED_COVERAGE="${COVERAGE_FILE}.filtered"

    # Match only files directly in the excluded package (no further "/" before
    # the filename), so excluding the agent root package (main.go) does not
    # also exclude its subpackages (agent/muzzle, agent/cert, etc.) — unlike
    # backend's EXCLUDE_PACKAGES entries, which intentionally exclude an
    # entire subtree (e.g. internal/trace/**).
    SED_PATTERN=""
    for pkg in "${EXCLUDE_PACKAGES[@]}"; do
        if [ -z "$SED_PATTERN" ]; then
            SED_PATTERN="\|^${pkg}/[^/]*\\.go:|d"
        else
            SED_PATTERN="${SED_PATTERN};\|^${pkg}/[^/]*\\.go:|d"
        fi
    done

    timeout 30 sed "$SED_PATTERN" "$COVERAGE_FILE" > "$FILTERED_COVERAGE" || {
        echo "Error: Coverage filtering failed or timed out"
        echo "Using unfiltered coverage file"
        cp "$COVERAGE_FILE" "$FILTERED_COVERAGE"
    }

    mv "$FILTERED_COVERAGE" "$COVERAGE_FILE"
    echo "Coverage filtering complete"
fi

if [ ! -f "$COVERAGE_FILE" ]; then
    echo "Error: coverage file not generated by go test"
    exit 1
fi

COVERAGE_OUTPUT=$(timeout 180 go tool cover -func="$COVERAGE_FILE" 2>&1) || {
    echo "Error: go tool cover failed or timed out after 180 seconds"
    echo "This may indicate corrupted coverage data or memory issues"
    exit 1
}

TOTAL_LINE=$(echo "$COVERAGE_OUTPUT" | awk '/^total:/ {line=$0} END {print line}')

if [ -z "$TOTAL_LINE" ]; then
    echo "Error: Coverage report missing 'total:' line"
    echo "Coverage output:"
    echo "$COVERAGE_OUTPUT"
    exit 1
fi

echo "$TOTAL_LINE"

STATEMENT_PERCENT=$(echo "$TOTAL_LINE" | awk '{
    if (NF < 3) {
        print "ERROR: Invalid coverage line format" > "/dev/stderr"
        exit 1
    }
    last_field = $NF
    if (last_field !~ /^[0-9]+(\.[0-9]+)?%$/) {
        printf "ERROR: Last field is not a valid percentage: %s\n", last_field > "/dev/stderr"
        exit 1
    }
    gsub(/%$/, "", last_field)
    print last_field
}')

if [ -z "$STATEMENT_PERCENT" ] || [ "$STATEMENT_PERCENT" = "ERROR" ]; then
    echo "Error: Could not extract coverage percentage from: $TOTAL_LINE"
    exit 1
fi

if ! echo "$STATEMENT_PERCENT" | grep -qE '^[0-9]+(\.[0-9]+)?$'; then
    echo "Error: Extracted coverage value is not numeric: '$STATEMENT_PERCENT'"
    echo "Source line: $TOTAL_LINE"
    exit 1
fi

# Compute line coverage directly from coverprofile blocks (authoritative gate in this script)
# Format per line:
#   file:startLine.startCol,endLine.endCol numStatements count
LINE_PERCENT=$(awk '
BEGIN {
    total_lines = 0
    covered_lines = 0
}
NR == 1 {
    next
}
{
    split($1, pos, ":")
    if (length(pos) < 2) {
        next
    }

    file = pos[1]
    split(pos[2], ranges, ",")
    split(ranges[1], start_parts, ".")
    split(ranges[2], end_parts, ".")

    start_line = start_parts[1] + 0
    end_line = end_parts[1] + 0
    count = $3 + 0

    if (start_line <= 0 || end_line <= 0 || end_line < start_line) {
        next
    }

    for (line = start_line; line <= end_line; line++) {
        key = file ":" line
        if (!(key in seen_total)) {
            seen_total[key] = 1
            total_lines++
        }
        if (count > 0 && !(key in seen_covered)) {
            seen_covered[key] = 1
            covered_lines++
        }
    }
}
END {
    if (total_lines == 0) {
        print "0.0"
        exit 0
    }
    printf "%.1f", (covered_lines * 100.0) / total_lines
}
' "$COVERAGE_FILE")

if [ -z "$LINE_PERCENT" ]; then
    echo "Error: Could not compute line coverage from $COVERAGE_FILE"
    exit 1
fi

if ! echo "$LINE_PERCENT" | grep -qE '^[0-9]+(\.[0-9]+)?$'; then
    echo "Error: Computed line coverage is not numeric: '$LINE_PERCENT'"
    exit 1
fi

echo "Statement coverage: ${STATEMENT_PERCENT}%"
echo "Line coverage: ${LINE_PERCENT}%"
echo "Coverage gate (line coverage): minimum required ${MIN_COVERAGE}%"

if awk -v current="$LINE_PERCENT" -v minimum="$MIN_COVERAGE" 'BEGIN { exit !(current + 0 < minimum + 0) }'; then
    echo "Coverage ${LINE_PERCENT}% is below required ${MIN_COVERAGE}% (set CHARON_AGENT_MIN_COVERAGE to override)"
    exit 1
fi

echo "Coverage requirement met"

if [ "$GO_TEST_STATUS" -ne 0 ]; then
    exit "$GO_TEST_STATUS"
fi
